name: PR Details

on: 
  pull_request:
    branches: [ master, node-v12 ]
    types: [opened, synchronize, reopened]
  push:
    branches: [ master, node-v12 ]

jobs:
  pr-details:
    name: Pr Details
    runs-on: ubuntu-latest
    
    steps:

      - name: â¬‡ï¸ Checkout Repository
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 12
          cache: 'npm'

      - name: ğŸ“¥ npm install
        uses: bahmutov/npm-install@v1.8.5
      
      - name: ğŸ”¬ Get PR
        run: npm run pr-details
        env: 
          GHT: ${{ secrets.GITHUB_TOKEN }}