name: âš™ï¸ Validate PR

on:
  pull_request:
    branches: [ newProduction ]
    types: [opened, synchronize, reopened]

jobs:
  validate:
    name: Pull Request Validation
    runs-on: ubuntu-latest
    
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: â¬‡ï¸ Checkout projectX
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 12
          # cache npm can be used only when there is a package-lock.json
          # cache: 'npm'

      - name: ğŸ“¥ npm install
        uses: bahmutov/npm-install@v1.8.5
        with:
          useLockFile: false

      - name: ğŸ”¬ Lint
        run: npm run lint
      
      - name: Validate Circular Dependencies
        run: npm run validate-circular-dependencies